### ISSUE TITLE
Drupal Content: Reduce content

### ISSUE THREAD

**Issue by jfrank-nih** [NCIOCPL/akumina-mynci#40]
Add a new method to the `DrupalContent` class called `reduceContent` or similar. This method should take as inputs:

- A content export object to work on
- The path within that object to the URL to look up in the URL coverter
- An instance of the URL converter class to look up items on

It should then:

- Iterate through every item in the given content object and do the following
- Look up the item in the URLConverter using the `lookupActive` method
    - May also need to use a `lookupActiveNID` method to ensure NID links are examined
- If the resulting URL from the converter is "Active" then do nothing
- If the resulting URL from the converter is not "Active" then delete the item from the content object

**Comment by erikscottmeyer** [comment]
As discussed, instead of deleting items marked not active, I'm going to set a boolean migrate variable to false; I'll set migrate to true for all content import objects by default, then flip it to false for the inactive ones in the types we're processing. We can then check for that on import into akumina,

**Comment by erikscottmeyer** [comment]
I added an OldPAth Sharepoint column to all of the content maps; this preserves the full path + slug in the Akumina objects.  I need to be able to lookup the full path + slug, not just the slugs, in my oldURL to newURL map (because slugs alone might not be unique), so I'm using this to give me that information
